"""
TASCK OS Seed Data - Nigerian Creative Economy Demo Data
"""
from datetime import datetime, timezone, timedelta
import random

def get_seed_data():
    """Generate comprehensive seed data for TASCK OS demo"""
    
    # Helper to generate dates
    now = datetime.now(timezone.utc)
    
    # TASCK Staff
    staff = [
        {
            "id": "staff-001",
            "email": "tunde@thetasck.com",
            "name": "Tunde Balogun",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Music and Entertainment",
            "artists_managed": ["sc-001", "sc-002", "sc-007", "sc-008"],
            "revenue_ytd": 134500000,
            "bio": "Senior Agent with 8+ years in entertainment management"
        },
        {
            "id": "staff-002",
            "email": "amaka@thetasck.com",
            "name": "Amaka Obi",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Fashion and Lifestyle",
            "artists_managed": ["sc-005", "sc-003", "sc-009"],
            "revenue_ytd": 109200000,
            "bio": "Specializes in fashion and lifestyle brand partnerships"
        },
        {
            "id": "staff-003",
            "email": "femi@thetasck.com",
            "name": "Femi Adeyinka",
            "role": "staff",
            "avatar": None,
            "location": "Abuja, Nigeria",
            "verified": True,
            "focus": "Sports and Brands",
            "artists_managed": ["sc-004", "sc-006"],
            "revenue_ytd": 98700000,
            "bio": "Expert in sports marketing and brand activations"
        },
        {
            "id": "staff-004",
            "email": "nkechi@thetasck.com",
            "name": "Nkechi Eze",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Emerging Talent",
            "artists_managed": ["sc-010"],
            "revenue_ytd": 42600000,
            "bio": "Scouts and develops emerging Nigerian talent"
        }
    ]
    
    # Brands
    brands = [
        {
            "id": "brand-001",
            "name": "MTN Nigeria",
            "category": "Telecoms",
            "marketing_budget": "₦15B",
            "contact_name": "Adia Sowho",
            "contact_title": "VP Marketing",
            "contact_email": "adia.sowho@mtn.ng",
            "relationship_score": 8.2,
            "total_revenue": 144000000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-002",
            "name": "Guinness Nigeria",
            "category": "Beverages (Diageo)",
            "marketing_budget": "₦8B",
            "contact_name": "Adenike Ogunlesi",
            "contact_title": "Head of Culture",
            "contact_email": "adenike@diageo-ng.com",
            "relationship_score": 9.1,
            "total_revenue": 132000000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-003",
            "name": "Pepsi Nigeria",
            "category": "Beverages (PepsiCo)",
            "marketing_budget": "₦5B",
            "contact_name": "Chidi Okeke",
            "contact_title": "Brand Director",
            "contact_email": "chidi.okeke@pepsico.com",
            "relationship_score": 8.8,
            "total_revenue": 85000000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-004",
            "name": "Coca-Cola Nigeria",
            "category": "Beverages",
            "marketing_budget": "₦7B",
            "contact_name": "Amina Bashir",
            "contact_title": "Marketing Lead",
            "contact_email": "amina.bashir@coca-cola.com",
            "relationship_score": 7.5,
            "total_revenue": 0,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-005",
            "name": "Access Bank",
            "category": "Banking",
            "marketing_budget": "₦4B",
            "contact_name": "Folake Ani-Mumuney",
            "contact_title": "GH Marketing",
            "contact_email": "folake@accessbankplc.com",
            "relationship_score": 6.2,
            "total_revenue": 0,
            "active_deals": 0,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-006",
            "name": "Flutterwave",
            "category": "Fintech",
            "marketing_budget": "₦1.5B",
            "contact_name": "Olugbenga Agboola",
            "contact_title": "CEO",
            "contact_email": "gb@flutterwave.com",
            "relationship_score": 5.8,
            "total_revenue": 0,
            "active_deals": 0,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-007",
            "name": "Jumia Nigeria",
            "category": "E-commerce",
            "marketing_budget": "₦2B",
            "contact_name": "Massimiliano Spalazzi",
            "contact_title": "CEO",
            "contact_email": "max@jumia.com",
            "relationship_score": 7.8,
            "total_revenue": 22000000,
            "active_deals": 0,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-008",
            "name": "Bolt Nigeria",
            "category": "Ride-hailing",
            "marketing_budget": "₦1B",
            "contact_name": "Femi Adeyemo",
            "contact_title": "Country Manager",
            "contact_email": "femi@bolt.eu",
            "relationship_score": 5.5,
            "total_revenue": 0,
            "active_deals": 0,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-009",
            "name": "Netflix Naija",
            "category": "Entertainment",
            "marketing_budget": "₦3B",
            "contact_name": "Dorothy Ghettuba",
            "contact_title": "Director Content",
            "contact_email": "dorothy@netflix.com",
            "relationship_score": 6.5,
            "total_revenue": 0,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-010",
            "name": "Boomplay",
            "category": "Music Platform",
            "marketing_budget": "₦600M",
            "contact_name": "Tosin Sorinola",
            "contact_title": "Head of Content",
            "contact_email": "tosin@boomplay.com",
            "relationship_score": 7.2,
            "total_revenue": 12000000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-011",
            "name": "Johnnie Walker (Diageo)",
            "category": "Spirits",
            "marketing_budget": "₦3B",
            "contact_name": "Mark Thompson",
            "contact_title": "Marketing Director",
            "contact_email": "mark.t@diageo.com",
            "relationship_score": 9.4,
            "total_revenue": 75000000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        },
        {
            "id": "brand-012",
            "name": "Cadbury Nigeria",
            "category": "FMCG",
            "marketing_budget": "₦1.5B",
            "contact_name": "Segun Ademola",
            "contact_title": "Brand Manager",
            "contact_email": "segun@cadbury.ng",
            "relationship_score": 8.0,
            "total_revenue": 24600000,
            "active_deals": 1,
            "location": "Lagos, Nigeria"
        }
    ]
    
    # Super Creatives (Artist Teams)
    super_creatives = [
        {
            "id": "sc-001",
            "email": "team@mavinrecords.com",
            "name": "Mavin Records Team",
            "role": "super_creative",
            "team_name": "Mavin Records",
            "principal_artist": "Don Jazzy",
            "genre": "Producer / Afrobeats",
            "spotify_listeners": "8.4M",
            "instagram_followers": "14.2M",
            "brand_value": "₦350M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 12450000,
            "escrowed": 9000000,
            "verified": True
        },
        {
            "id": "sc-002",
            "email": "team@spaceship.com",
            "name": "Spaceship Team",
            "role": "super_creative",
            "team_name": "Spaceship",
            "principal_artist": "Burna Boy",
            "genre": "Afro-fusion",
            "spotify_listeners": "42.3M",
            "instagram_followers": "12.8M",
            "brand_value": "₦800M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 45000000,
            "escrowed": 15000000,
            "verified": True
        },
        {
            "id": "sc-003",
            "email": "team@dmw.com",
            "name": "DMW Team",
            "role": "super_creative",
            "team_name": "DMW",
            "principal_artist": "Davido",
            "genre": "Afropop",
            "spotify_listeners": "31.2M",
            "instagram_followers": "28.1M",
            "brand_value": "₦750M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 38000000,
            "escrowed": 12000000,
            "verified": True
        },
        {
            "id": "sc-004",
            "email": "team@starboy.com",
            "name": "Starboy Team",
            "role": "super_creative",
            "team_name": "Starboy",
            "principal_artist": "Wizkid",
            "genre": "Afrobeats",
            "spotify_listeners": "38.7M",
            "instagram_followers": "17.4M",
            "brand_value": "₦820M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 52000000,
            "escrowed": 8000000,
            "verified": True
        },
        {
            "id": "sc-005",
            "email": "team@leadingvibes.com",
            "name": "Leading Vibes Team",
            "role": "super_creative",
            "team_name": "Leading Vibes",
            "principal_artist": "Tems",
            "genre": "Alt R&B / Afrobeats",
            "spotify_listeners": "28.9M",
            "instagram_followers": "8.6M",
            "brand_value": "₦500M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 28000000,
            "escrowed": 5000000,
            "verified": True
        },
        {
            "id": "sc-006",
            "email": "team@ybnl.com",
            "name": "YBNL Team",
            "role": "super_creative",
            "team_name": "YBNL",
            "principal_artist": "Olamide",
            "genre": "Yoruba Rap / Afropop",
            "spotify_listeners": "7.1M",
            "instagram_followers": "11.2M",
            "brand_value": "₦250M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 15000000,
            "escrowed": 3000000,
            "verified": True
        },
        {
            "id": "sc-007",
            "email": "team@remateam.com",
            "name": "Rema Team",
            "role": "super_creative",
            "team_name": "Rema Team",
            "principal_artist": "Rema",
            "genre": "Afrorave",
            "spotify_listeners": "45.1M",
            "instagram_followers": "9.2M",
            "brand_value": "₦450M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 32000000,
            "escrowed": 6000000,
            "verified": True
        },
        {
            "id": "sc-008",
            "email": "team@mavintalent.com",
            "name": "Mavin Talent Team",
            "role": "super_creative",
            "team_name": "Mavin Talent",
            "principal_artist": "Ayra Starr",
            "genre": "Afropop",
            "spotify_listeners": "22.3M",
            "instagram_followers": "7.8M",
            "brand_value": "₦280M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 18000000,
            "escrowed": 4000000,
            "verified": True
        },
        {
            "id": "sc-009",
            "email": "team@tiwa.com",
            "name": "Tiwa Savage Team",
            "role": "super_creative",
            "team_name": "Tiwa Savage Team",
            "principal_artist": "Tiwa Savage",
            "genre": "Afrobeats / Pop",
            "spotify_listeners": "12.4M",
            "instagram_followers": "14.1M",
            "brand_value": "₦300M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 22000000,
            "escrowed": 3500000,
            "verified": True
        },
        {
            "id": "sc-010",
            "email": "team@asake.com",
            "name": "Asake Team",
            "role": "super_creative",
            "team_name": "Asake Team",
            "principal_artist": "Asake",
            "genre": "Street-pop",
            "spotify_listeners": "18.2M",
            "instagram_followers": "5.9M",
            "brand_value": "₦320M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 25000000,
            "escrowed": 5000000,
            "verified": True
        }
    ]
    
    # Creatives (Freelancers)
    creatives = [
        {
            "id": "cr-001",
            "email": "kelechi@studio.com",
            "name": "Kelechi Amadi-Obi",
            "role": "creative",
            "skills": ["Photography", "Art Direction", "Editorial"],
            "day_rate": 350000,
            "rating": 4.9,
            "reliability": 97,
            "completed_projects": 14,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2875000,
            "verified": True,
            "tagline": "Award-winning photographer. Editorial and concert specialist.",
            "bio": "With over 15 years of experience, I've worked with Africa's top artists and brands."
        },
        {
            "id": "cr-002",
            "email": "ade@films.com",
            "name": "Ade Adesanya",
            "role": "creative",
            "skills": ["Videography", "Cinematography", "Music Videos"],
            "day_rate": 280000,
            "rating": 4.8,
            "reliability": 91,
            "completed_projects": 11,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1950000,
            "verified": True,
            "tagline": "Director and cinematographer. Music video and brand content.",
            "bio": "Specializing in music videos and brand content that tells compelling stories."
        },
        {
            "id": "cr-003",
            "email": "tolu@design.com",
            "name": "Tolu Akinwande",
            "role": "creative",
            "skills": ["Graphic Design", "Visual Identity", "Campaign Design"],
            "day_rate": 150000,
            "rating": 4.9,
            "reliability": 98,
            "completed_projects": 22,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1250000,
            "verified": True,
            "tagline": "Visual identity and campaign design. Clean, bold aesthetics.",
            "bio": "Creating visual identities that stand out and drive brand recognition."
        },
        {
            "id": "cr-004",
            "email": "chidinma@social.com",
            "name": "Chidinma Okafor",
            "role": "creative",
            "skills": ["Social Media", "Content Strategy", "Community Management"],
            "day_rate": 120000,
            "rating": 4.7,
            "reliability": 94,
            "completed_projects": 18,
            "location": "Lagos, Nigeria",
            "wallet_balance": 980000,
            "verified": True,
            "tagline": "Social strategy and content management. 500M+ impressions managed.",
            "bio": "Helping brands connect with their audience through strategic social content."
        },
        {
            "id": "cr-005",
            "email": "seun@stages.com",
            "name": "Seun Ogunlesi",
            "role": "creative",
            "skills": ["Stage Design", "Event Production", "Immersive Experiences"],
            "day_rate": 400000,
            "rating": 5.0,
            "reliability": 100,
            "completed_projects": 7,
            "location": "Lagos, Nigeria",
            "wallet_balance": 3500000,
            "verified": True,
            "tagline": "Immersive stage experiences. Concerts and corporate events.",
            "bio": "Designing unforgettable stage experiences for Africa's biggest concerts."
        },
        {
            "id": "cr-006",
            "email": "simi@sound.com",
            "name": "Simi Oluwadare",
            "role": "creative",
            "skills": ["Sound Engineering", "Live Sound", "Studio Mixing"],
            "day_rate": 250000,
            "rating": 4.8,
            "reliability": 95,
            "completed_projects": 9,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1800000,
            "verified": True,
            "tagline": "Live sound and studio mixing. Major festival experience.",
            "bio": "Delivering crystal-clear sound for live events and studio recordings."
        },
        {
            "id": "cr-007",
            "email": "funke@styling.com",
            "name": "Funke Adeyemi",
            "role": "creative",
            "skills": ["Styling", "Fashion", "Celebrity Wardrobe"],
            "day_rate": 200000,
            "rating": 4.9,
            "reliability": 96,
            "completed_projects": 16,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2100000,
            "verified": True,
            "tagline": "Celebrity and editorial styling. Worked with top Nollywood talent.",
            "bio": "Styling Africa's biggest stars for red carpets and campaigns."
        },
        {
            "id": "cr-008",
            "email": "emeka@motion.com",
            "name": "Emeka Nwosu",
            "role": "creative",
            "skills": ["Motion Graphics", "Animation", "After Effects"],
            "day_rate": 180000,
            "rating": 4.7,
            "reliability": 92,
            "completed_projects": 13,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1450000,
            "verified": True,
            "tagline": "After Effects and Cinema 4D specialist. Brand animations.",
            "bio": "Bringing brands to life through dynamic motion graphics."
        },
        {
            "id": "cr-009",
            "email": "yemi@copy.com",
            "name": "Yemi Adebayo",
            "role": "creative",
            "skills": ["Copywriting", "Brand Voice", "Campaign Copy"],
            "day_rate": 100000,
            "rating": 4.8,
            "reliability": 97,
            "completed_projects": 25,
            "location": "Lagos, Nigeria",
            "wallet_balance": 850000,
            "verified": True,
            "tagline": "Brand voice and campaign copy. Bilingual English/Yoruba.",
            "bio": "Crafting words that resonate with Nigerian audiences."
        },
        {
            "id": "cr-010",
            "email": "bola@pr.com",
            "name": "Bola Okonkwo",
            "role": "creative",
            "skills": ["PR", "Media Relations", "Press Coverage"],
            "day_rate": 300000,
            "rating": 4.6,
            "reliability": 90,
            "completed_projects": 8,
            "location": "Abuja, Nigeria",
            "wallet_balance": 2200000,
            "verified": True,
            "tagline": "Media relations and press coverage. Government and entertainment.",
            "bio": "Connecting brands with media outlets across Nigeria."
        },
        {
            "id": "cr-011",
            "email": "ngozi@makeup.com",
            "name": "Ngozi Okafor",
            "role": "creative",
            "skills": ["Makeup Artistry", "Editorial Makeup", "Film"],
            "day_rate": 150000,
            "rating": 5.0,
            "reliability": 99,
            "completed_projects": 20,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1650000,
            "verified": True,
            "tagline": "Editorial and film makeup. Natural beauty specialist.",
            "bio": "Enhancing natural beauty for editorial and film productions."
        },
        {
            "id": "cr-012",
            "email": "ibrahim@beats.com",
            "name": "Ibrahim Hassan",
            "role": "creative",
            "skills": ["Music Production", "Beat Making", "Afrobeats"],
            "day_rate": 200000,
            "rating": 4.8,
            "reliability": 93,
            "completed_projects": 12,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1350000,
            "verified": True,
            "tagline": "Beat maker and producer. Afrobeats and amapiano.",
            "bio": "Creating the sounds that define Nigerian music."
        },
        {
            "id": "cr-013",
            "email": "amara@content.com",
            "name": "Amara Eze",
            "role": "creative",
            "skills": ["Content Writing", "Blog Posts", "Brand Storytelling"],
            "day_rate": 80000,
            "rating": 4.9,
            "reliability": 98,
            "completed_projects": 30,
            "location": "Lagos, Nigeria",
            "wallet_balance": 720000,
            "verified": True,
            "tagline": "Blog posts, press releases, brand storytelling.",
            "bio": "Telling brand stories that connect and convert."
        },
        {
            "id": "cr-014",
            "email": "dayo@events.com",
            "name": "Dayo Olatunji",
            "role": "creative",
            "skills": ["Event Planning", "Logistics", "Large-scale Events"],
            "day_rate": 350000,
            "rating": 4.7,
            "reliability": 94,
            "completed_projects": 6,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2800000,
            "verified": True,
            "tagline": "Large-scale events. 500+ capacity. Logistics specialist.",
            "bio": "Orchestrating flawless events for thousands of attendees."
        },
        {
            "id": "cr-015",
            "email": "zainab@uiux.com",
            "name": "Zainab Mohammed",
            "role": "creative",
            "skills": ["UI/UX Design", "App Design", "Prototyping"],
            "day_rate": 200000,
            "rating": 4.8,
            "reliability": 95,
            "completed_projects": 15,
            "location": "Abuja, Nigeria",
            "wallet_balance": 1900000,
            "verified": True,
            "tagline": "App and web design. User research and prototyping.",
            "bio": "Designing digital experiences that users love."
        },
        {
            "id": "cr-016",
            "email": "chukwu@edit.com",
            "name": "Chukwuemeka Obi",
            "role": "creative",
            "skills": ["Video Editing", "Social Cutdowns", "Long-form"],
            "day_rate": 160000,
            "rating": 4.7,
            "reliability": 93,
            "completed_projects": 19,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1100000,
            "verified": True,
            "tagline": "Fast turnaround editor. Social cutdowns and long-form.",
            "bio": "Editing content that performs across all platforms."
        },
        {
            "id": "cr-017",
            "email": "aisha@photos.com",
            "name": "Aisha Bello",
            "role": "creative",
            "skills": ["Photography", "Portrait", "Corporate"],
            "day_rate": 250000,
            "rating": 4.8,
            "reliability": 96,
            "completed_projects": 10,
            "location": "Abuja, Nigeria",
            "wallet_balance": 1750000,
            "verified": True,
            "tagline": "Portrait and corporate photography. Clean and professional.",
            "bio": "Capturing professional moments for corporate clients."
        },
        {
            "id": "cr-018",
            "email": "olumide@creative.com",
            "name": "Olumide Bakare",
            "role": "creative",
            "skills": ["Creative Direction", "Campaign Lead", "Concept"],
            "day_rate": 400000,
            "rating": 4.9,
            "reliability": 97,
            "completed_projects": 8,
            "location": "Lagos, Nigeria",
            "wallet_balance": 3200000,
            "verified": True,
            "tagline": "Campaign creative lead. Concept to execution.",
            "bio": "Leading creative campaigns from concept to execution."
        },
        {
            "id": "cr-019",
            "email": "blessing@scripts.com",
            "name": "Blessing Nwachukwu",
            "role": "creative",
            "skills": ["Scriptwriting", "TVC Scripts", "Documentary"],
            "day_rate": 120000,
            "rating": 4.6,
            "reliability": 91,
            "completed_projects": 14,
            "location": "Lagos, Nigeria",
            "wallet_balance": 920000,
            "verified": True,
            "tagline": "TVC scripts, brand films, documentary.",
            "bio": "Writing scripts that bring brand stories to life."
        },
        {
            "id": "cr-020",
            "email": "tunde@sounddesign.com",
            "name": "Tunde Oyelola",
            "role": "creative",
            "skills": ["Sound Design", "Foley", "Mixing"],
            "day_rate": 180000,
            "rating": 4.7,
            "reliability": 92,
            "completed_projects": 11,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1380000,
            "verified": True,
            "tagline": "Sound design for film and ads. Foley and mixing.",
            "bio": "Creating immersive soundscapes for visual content."
        }
    ]
    
    # Deals
    deals = [
        {
            "id": "deal-001",
            "deal_id": "TK-2026-0042",
            "title": "Spaceship (Burna Boy) x Guinness Nigeria - 'Twice As Tall' Anniversary Activation",
            "brand_id": "brand-002",
            "brand_name": "Guinness Nigeria",
            "super_creative_id": "sc-002",
            "super_creative_name": "Spaceship (Burna Boy)",
            "agent_id": "staff-001",
            "agent_name": "Tunde Balogun",
            "status": "awaiting_terms",
            "value": 45000000,
            "commission_rate": 0.15,
            "commission_value": 6750000,
            "priority": "high",
            "campaign_type": "Brand Activation",
            "last_activity": (now - timedelta(hours=2)).isoformat()
        },
        {
            "id": "deal-002",
            "deal_id": "TK-2026-0043",
            "title": "Leading Vibes (Tems) x MTN Nigeria - Brand Ambassador 2026",
            "brand_id": "brand-001",
            "brand_name": "MTN Nigeria",
            "super_creative_id": "sc-005",
            "super_creative_name": "Leading Vibes (Tems)",
            "agent_id": "staff-002",
            "agent_name": "Amaka Obi",
            "status": "scoping",
            "value": 62000000,
            "commission_rate": 0.15,
            "commission_value": 9300000,
            "priority": "high",
            "campaign_type": "Brand Ambassador",
            "last_activity": now.isoformat()
        },
        {
            "id": "deal-003",
            "deal_id": "TK-2026-0044",
            "title": "DMW (Davido) x Pepsi Nigeria - 'Street Vibes' National Campaign",
            "brand_id": "brand-003",
            "brand_name": "Pepsi Nigeria",
            "super_creative_id": "sc-003",
            "super_creative_name": "DMW (Davido)",
            "agent_id": "staff-002",
            "agent_name": "Amaka Obi",
            "status": "active",
            "value": 85000000,
            "commission_rate": 0.15,
            "commission_value": 12750000,
            "priority": "medium",
            "campaign_type": "National Campaign",
            "last_activity": (now - timedelta(days=1)).isoformat()
        },
        {
            "id": "deal-004",
            "deal_id": "TK-2026-0045",
            "title": "Coke Studio Africa 2026 - Multiple Artists",
            "brand_id": "brand-004",
            "brand_name": "Coca-Cola Nigeria",
            "super_creative_id": None,
            "super_creative_name": "Multiple TBD",
            "agent_id": "staff-001",
            "agent_name": "Tunde Balogun",
            "status": "scoping",
            "value": 150000000,
            "commission_rate": 0.15,
            "commission_value": 22500000,
            "priority": "high",
            "campaign_type": "Content Series",
            "last_activity": now.isoformat()
        },
        {
            "id": "deal-005",
            "deal_id": "TK-2026-0046",
            "title": "Mavin Records (Don Jazzy) x Johnnie Walker - 'Walk With Giants'",
            "brand_id": "brand-011",
            "brand_name": "Johnnie Walker (Diageo)",
            "super_creative_id": "sc-001",
            "super_creative_name": "Mavin Records (Don Jazzy)",
            "agent_id": "staff-001",
            "agent_name": "Tunde Balogun",
            "status": "active",
            "value": 25000000,
            "commission_rate": 0.15,
            "commission_value": 3750000,
            "priority": "medium",
            "campaign_type": "Brand Ambassador",
            "last_activity": (now - timedelta(weeks=2)).isoformat()
        },
        {
            "id": "deal-006",
            "deal_id": "TK-2026-0047",
            "title": "Mavin Records (Don Jazzy) x Cadbury Nigeria - Social Campaign",
            "brand_id": "brand-012",
            "brand_name": "Cadbury Nigeria",
            "super_creative_id": "sc-001",
            "super_creative_name": "Mavin Records (Don Jazzy)",
            "agent_id": "staff-001",
            "agent_name": "Tunde Balogun",
            "status": "active",
            "value": 8200000,
            "commission_rate": 0.15,
            "commission_value": 1230000,
            "priority": "low",
            "campaign_type": "Social Media",
            "last_activity": (now - timedelta(weeks=1)).isoformat()
        },
        {
            "id": "deal-007",
            "deal_id": "TK-2026-0048",
            "title": "Rema Team x Boomplay - Exclusive Partnership",
            "brand_id": "brand-010",
            "brand_name": "Boomplay",
            "super_creative_id": "sc-007",
            "super_creative_name": "Rema Team",
            "agent_id": "staff-001",
            "agent_name": "Tunde Balogun",
            "status": "active",
            "value": 12000000,
            "commission_rate": 0.15,
            "commission_value": 1800000,
            "priority": "medium",
            "campaign_type": "Content Series",
            "last_activity": (now - timedelta(days=4)).isoformat()
        },
        {
            "id": "deal-008",
            "deal_id": "TK-2026-0049",
            "title": "Starboy (Wizkid) x Diageo Nigeria - Legacy Series",
            "brand_id": "brand-011",
            "brand_name": "Diageo Nigeria",
            "super_creative_id": "sc-004",
            "super_creative_name": "Starboy (Wizkid)",
            "agent_id": "staff-003",
            "agent_name": "Femi Adeyinka",
            "status": "active",
            "value": 30000000,
            "commission_rate": 0.15,
            "commission_value": 4500000,
            "priority": "medium",
            "campaign_type": "Brand Campaign",
            "last_activity": (now - timedelta(days=3)).isoformat()
        },
        {
            "id": "deal-009",
            "deal_id": "TK-2026-0050",
            "title": "Mavin Talent (Fireboy DML) x UBA Foundation - Financial Literacy",
            "brand_id": "brand-005",
            "brand_name": "UBA Foundation",
            "super_creative_id": "sc-008",
            "super_creative_name": "Mavin Talent (Fireboy DML)",
            "agent_id": "staff-004",
            "agent_name": "Nkechi Eze",
            "status": "awaiting_terms",
            "value": 18000000,
            "commission_rate": 0.15,
            "commission_value": 2700000,
            "priority": "medium",
            "campaign_type": "Campaign",
            "last_activity": (now - timedelta(days=1)).isoformat()
        },
        {
            "id": "deal-010",
            "deal_id": "TK-2026-0051",
            "title": "Netflix Naija Premiere Activation",
            "brand_id": "brand-009",
            "brand_name": "Netflix Naija",
            "super_creative_id": None,
            "super_creative_name": "TBD",
            "agent_id": "staff-002",
            "agent_name": "Amaka Obi",
            "status": "scoping",
            "value": 35000000,
            "commission_rate": 0.15,
            "commission_value": 5250000,
            "priority": "medium",
            "campaign_type": "Event",
            "last_activity": (now - timedelta(days=2)).isoformat()
        },
        {
            "id": "deal-011",
            "deal_id": "TK-2026-0038",
            "title": "Flutterwave Creator Economy Launch",
            "brand_id": "brand-006",
            "brand_name": "Flutterwave",
            "super_creative_id": None,
            "super_creative_name": "TBD",
            "agent_id": "staff-003",
            "agent_name": "Femi Adeyinka",
            "status": "discovery",
            "value": 40000000,
            "commission_rate": 0.15,
            "commission_value": 6000000,
            "priority": "medium",
            "campaign_type": "Product Launch",
            "last_activity": (now - timedelta(days=3)).isoformat()
        },
        {
            "id": "deal-012",
            "deal_id": "TK-2026-0035",
            "title": "Indomie Nigeria x Artist TBD",
            "brand_id": "brand-007",
            "brand_name": "Indomie Nigeria",
            "super_creative_id": None,
            "super_creative_name": None,
            "agent_id": "staff-004",
            "agent_name": "Nkechi Eze",
            "status": "lead",
            "value": 15000000,
            "commission_rate": 0.15,
            "commission_value": 2250000,
            "priority": "low",
            "campaign_type": "TBD",
            "last_activity": (now - timedelta(weeks=2)).isoformat()
        },
        {
            "id": "deal-013",
            "deal_id": "TK-2026-0030",
            "title": "YBNL (Olamide) x Jumia - 'Street to Screen'",
            "brand_id": "brand-007",
            "brand_name": "Jumia Nigeria",
            "super_creative_id": "sc-006",
            "super_creative_name": "YBNL (Olamide)",
            "agent_id": "staff-003",
            "agent_name": "Femi Adeyinka",
            "status": "closed_won",
            "value": 22000000,
            "commission_rate": 0.15,
            "commission_value": 3300000,
            "priority": "low",
            "campaign_type": "E-Commerce Campaign",
            "last_activity": (now - timedelta(weeks=3)).isoformat()
        },
        {
            "id": "deal-014",
            "deal_id": "TK-2026-0028",
            "title": "Asake Team x Globacom - Brand Deal",
            "brand_id": "brand-001",
            "brand_name": "Globacom",
            "super_creative_id": "sc-010",
            "super_creative_name": "Asake Team",
            "agent_id": "staff-004",
            "agent_name": "Nkechi Eze",
            "status": "closed_lost",
            "value": 35000000,
            "commission_rate": 0.15,
            "commission_value": 0,
            "priority": "low",
            "campaign_type": "Brand Ambassador",
            "last_activity": (now - timedelta(days=2)).isoformat()
        }
    ]
    
    # Projects
    projects = [
        {
            "id": "proj-001",
            "project_id": "PRJ-2026-0018",
            "title": "Pepsi Nigeria x DMW (Davido) - 'Street Vibes' National Campaign",
            "brand_id": "brand-003",
            "brand_name": "Pepsi Nigeria",
            "super_creative_id": "sc-003",
            "super_creative_name": "DMW (Davido)",
            "deal_id": "deal-003",
            "status": "active",
            "budget": 85000000,
            "escrowed": 72000000,
            "released": 48200000,
            "start_date": "2026-01-15",
            "end_date": "2026-06-30",
            "completion": 62,
            "opportunities_count": 15,
            "opportunities_filled": 12,
            "tasks_total": 87,
            "tasks_completed": 54
        },
        {
            "id": "proj-002",
            "project_id": "PRJ-2026-0019",
            "title": "Mavin All-Stars Concert 2026",
            "brand_id": None,
            "brand_name": None,
            "super_creative_id": "sc-001",
            "super_creative_name": "Mavin Records (Don Jazzy)",
            "deal_id": None,
            "status": "active",
            "budget": 15000000,
            "escrowed": 9000000,
            "released": 4500000,
            "start_date": "2026-02-15",
            "end_date": "2026-04-30",
            "completion": 68,
            "opportunities_count": 12,
            "opportunities_filled": 8,
            "tasks_total": 34,
            "tasks_completed": 22
        },
        {
            "id": "proj-003",
            "project_id": "PRJ-2026-0020",
            "title": "Don Jazzy x Cadbury Social Campaign",
            "brand_id": "brand-012",
            "brand_name": "Cadbury Nigeria",
            "super_creative_id": "sc-001",
            "super_creative_name": "Mavin Records (Don Jazzy)",
            "deal_id": "deal-006",
            "status": "active",
            "budget": 8200000,
            "escrowed": 6500000,
            "released": 2800000,
            "start_date": "2026-02-01",
            "end_date": "2026-04-15",
            "completion": 45,
            "opportunities_count": 4,
            "opportunities_filled": 4,
            "tasks_total": 14,
            "tasks_completed": 6
        },
        {
            "id": "proj-004",
            "project_id": "PRJ-2026-0021",
            "title": "Rema x Boomplay Exclusive Content",
            "brand_id": "brand-010",
            "brand_name": "Boomplay",
            "super_creative_id": "sc-007",
            "super_creative_name": "Rema Team",
            "deal_id": "deal-007",
            "status": "active",
            "budget": 12000000,
            "escrowed": 8000000,
            "released": 3200000,
            "start_date": "2026-02-10",
            "end_date": "2026-05-10",
            "completion": 30,
            "opportunities_count": 5,
            "opportunities_filled": 4,
            "tasks_total": 18,
            "tasks_completed": 5
        },
        {
            "id": "proj-005",
            "project_id": "PRJ-2026-0022",
            "title": "Wizkid x Diageo Legacy Series",
            "brand_id": "brand-011",
            "brand_name": "Diageo Nigeria",
            "super_creative_id": "sc-004",
            "super_creative_name": "Starboy (Wizkid)",
            "deal_id": "deal-008",
            "status": "active",
            "budget": 30000000,
            "escrowed": 22000000,
            "released": 7500000,
            "start_date": "2026-01-20",
            "end_date": "2026-06-20",
            "completion": 25,
            "opportunities_count": 8,
            "opportunities_filled": 6,
            "tasks_total": 24,
            "tasks_completed": 6
        },
        {
            "id": "proj-006",
            "project_id": "PRJ-2026-0015",
            "title": "YBNL x Jumia - 'Street to Screen'",
            "brand_id": "brand-007",
            "brand_name": "Jumia Nigeria",
            "super_creative_id": "sc-006",
            "super_creative_name": "YBNL (Olamide)",
            "deal_id": "deal-013",
            "status": "completed",
            "budget": 22000000,
            "escrowed": 0,
            "released": 21450000,
            "start_date": "2025-12-01",
            "end_date": "2026-02-28",
            "completion": 100,
            "opportunities_count": 8,
            "opportunities_filled": 8,
            "tasks_total": 45,
            "tasks_completed": 45
        },
        {
            "id": "proj-007",
            "project_id": "PRJ-2026-0023",
            "title": "Mavin Artist Development Program",
            "brand_id": None,
            "brand_name": None,
            "super_creative_id": "sc-001",
            "super_creative_name": "Mavin Records (Don Jazzy)",
            "deal_id": None,
            "status": "staffing",
            "budget": 5000000,
            "escrowed": 2000000,
            "released": 0,
            "start_date": "2026-03-01",
            "end_date": "2026-06-30",
            "completion": 15,
            "opportunities_count": 6,
            "opportunities_filled": 2,
            "tasks_total": 20,
            "tasks_completed": 1
        }
    ]
    
    # Opportunities
    opportunities = [
        {
            "id": "opp-001",
            "project_id": "proj-002",
            "project_title": "Mavin All-Stars Concert 2026",
            "role": "Lead Photographer",
            "description": "Capture high-quality event photography for Mavin All-Stars Concert",
            "budget": 1500000,
            "status": "in_progress",
            "skills_required": ["Photography", "Event", "Concert", "Editorial"],
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "deadline": "2026-04-30",
            "duration": "6 weeks",
            "tasks_count": 8,
            "tasks_completed": 5,
            "client_name": "Mavin Records",
            "client_type": "super_creative"
        },
        {
            "id": "opp-002",
            "project_id": "proj-002",
            "project_title": "Mavin All-Stars Concert 2026",
            "role": "Videographer (BTS)",
            "description": "Behind-the-scenes video documentation",
            "budget": 1200000,
            "status": "in_progress",
            "skills_required": ["Videography", "Documentary", "BTS"],
            "creative_id": "cr-002",
            "creative_name": "Ade Adesanya",
            "deadline": "2026-04-30",
            "duration": "6 weeks",
            "tasks_count": 6,
            "tasks_completed": 4,
            "client_name": "Mavin Records",
            "client_type": "super_creative"
        },
        {
            "id": "opp-003",
            "project_id": "proj-002",
            "project_title": "Mavin All-Stars Concert 2026",
            "role": "MC / Host",
            "description": "Event MC and host for concert",
            "budget": 2000000,
            "status": "open",
            "skills_required": ["MC", "Hosting", "Entertainment"],
            "creative_id": None,
            "creative_name": None,
            "deadline": "2026-03-05",
            "duration": "1 day + prep",
            "tasks_count": 0,
            "tasks_completed": 0,
            "client_name": "Mavin Records",
            "client_type": "super_creative"
        },
        {
            "id": "opp-004",
            "project_id": "proj-002",
            "project_title": "Mavin All-Stars Concert 2026",
            "role": "Lighting Designer",
            "description": "Stage lighting design and execution",
            "budget": 1200000,
            "status": "open",
            "skills_required": ["Lighting", "Stage Design", "Events"],
            "creative_id": None,
            "creative_name": None,
            "deadline": "2026-03-10",
            "duration": "4 weeks",
            "tasks_count": 0,
            "tasks_completed": 0,
            "client_name": "Mavin Records",
            "client_type": "super_creative"
        },
        {
            "id": "opp-005",
            "project_id": "proj-003",
            "project_title": "Don Jazzy x Cadbury Social Campaign",
            "role": "Photographer",
            "description": "Product lifestyle photography for social media campaign",
            "budget": 750000,
            "status": "in_progress",
            "skills_required": ["Photography", "Product", "Lifestyle"],
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "deadline": "2026-04-15",
            "duration": "2 months",
            "tasks_count": 4,
            "tasks_completed": 2,
            "client_name": "Cadbury Nigeria",
            "client_type": "brand"
        },
        {
            "id": "opp-006",
            "project_id": "proj-001",
            "project_title": "Pepsi Street Vibes Campaign",
            "role": "Lead Videographer",
            "description": "TVC and content production for national campaign",
            "budget": 3500000,
            "status": "in_progress",
            "skills_required": ["Videography", "TVC", "Commercials"],
            "creative_id": "cr-002",
            "creative_name": "Ade Adesanya",
            "deadline": "2026-06-30",
            "duration": "5 months",
            "tasks_count": 12,
            "tasks_completed": 7,
            "client_name": "Pepsi Nigeria",
            "client_type": "brand"
        },
        {
            "id": "opp-007",
            "project_id": "proj-004",
            "project_title": "Rema x Boomplay Exclusive",
            "role": "Campaign Photographer",
            "description": "Exclusive content photography for Boomplay partnership",
            "budget": 2200000,
            "status": "open",
            "skills_required": ["Photography", "Studio", "Editorial"],
            "creative_id": None,
            "creative_name": None,
            "deadline": "2026-03-10",
            "duration": "3 months",
            "tasks_count": 0,
            "tasks_completed": 0,
            "client_name": "Rema Team",
            "client_type": "super_creative"
        },
        {
            "id": "opp-008",
            "project_id": "proj-004",
            "project_title": "Rema x Boomplay Exclusive",
            "role": "Social Media Manager",
            "description": "Manage social content for Boomplay partnership",
            "budget": 1000000,
            "status": "in_progress",
            "skills_required": ["Social Media", "Content Strategy"],
            "creative_id": "cr-004",
            "creative_name": "Chidinma Okafor",
            "deadline": "2026-05-10",
            "duration": "3 months",
            "tasks_count": 6,
            "tasks_completed": 2,
            "client_name": "Rema Team",
            "client_type": "super_creative"
        }
    ]
    
    # Tasks
    tasks = [
        {
            "id": "task-001",
            "opportunity_id": "opp-005",
            "project_id": "proj-003",
            "title": "Product lifestyle shoot - Set 1",
            "description": "15 edited lifestyle photos (3000x2000px, 300dpi) + 5 BTS shots",
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "status": "approved",
            "due_date": "2026-02-20",
            "payment_amount": 187500
        },
        {
            "id": "task-002",
            "opportunity_id": "opp-005",
            "project_id": "proj-003",
            "title": "Product lifestyle shoot - Set 2",
            "description": "15 edited lifestyle photos + 5 BTS shots",
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "status": "approved",
            "due_date": "2026-02-28",
            "payment_amount": 187500
        },
        {
            "id": "task-003",
            "opportunity_id": "opp-005",
            "project_id": "proj-003",
            "title": "Product lifestyle shoot - Set 3",
            "description": "15 edited lifestyle photos + 5 BTS shots",
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "status": "submitted",
            "due_date": "2026-03-04",
            "payment_amount": 187500
        },
        {
            "id": "task-004",
            "opportunity_id": "opp-005",
            "project_id": "proj-003",
            "title": "Product lifestyle shoot - Set 4",
            "description": "15 edited lifestyle photos + 5 BTS shots",
            "creative_id": "cr-001",
            "creative_name": "Kelechi Amadi-Obi",
            "status": "in_progress",
            "due_date": "2026-03-10",
            "payment_amount": 187500
        },
        {
            "id": "task-005",
            "opportunity_id": "opp-006",
            "project_id": "proj-001",
            "title": "Hero TVC - Rough Cut",
            "description": "60-second hero TVC rough cut for review",
            "creative_id": "cr-002",
            "creative_name": "Ade Adesanya",
            "status": "submitted",
            "due_date": "2026-03-01",
            "payment_amount": 500000
        },
        {
            "id": "task-006",
            "opportunity_id": "opp-006",
            "project_id": "proj-001",
            "title": "BTS Video Edit v2",
            "description": "Behind-the-scenes content edit version 2",
            "creative_id": "cr-002",
            "creative_name": "Ade Adesanya",
            "status": "revision_requested",
            "due_date": "2026-03-02",
            "payment_amount": 250000
        }
    ]
    
    # Activity Feed
    activities = [
        {
            "id": "act-001",
            "entity_type": "deal",
            "entity_id": "deal-001",
            "action": "budget_approved",
            "description": "Guinness Nigeria approved ₦45M campaign budget for Burna Boy 'Twice As Tall' anniversary activation. Contract pending signature.",
            "metadata": {"status": "success"},
            "created_at": (now - timedelta(hours=2)).isoformat()
        },
        {
            "id": "act-002",
            "entity_type": "deal",
            "entity_id": "deal-002",
            "action": "counter_offer",
            "description": "MTN counter-offered on Tems brand ambassador deal. New terms: ₦62M/year (was ₦75M). Awaiting response.",
            "metadata": {"status": "warning"},
            "created_at": (now - timedelta(hours=5)).isoformat()
        },
        {
            "id": "act-003",
            "entity_type": "deal",
            "entity_id": "deal-004",
            "action": "opportunity_detected",
            "description": "New opportunity detected: Coca-Cola Africa launching 'Coke Studio Africa 2026' - Budget: $2.5M. AI Match: Wizkid (94%), Ayra Starr (89%), Rema (87%).",
            "metadata": {"status": "info"},
            "created_at": (now - timedelta(hours=8)).isoformat()
        },
        {
            "id": "act-004",
            "entity_type": "deal",
            "entity_id": "deal-009",
            "action": "contract_signed",
            "description": "UBA Foundation signed ₦18M deal for Fireboy DML financial literacy campaign. Fulfillment starts March 15.",
            "metadata": {"status": "success"},
            "created_at": (now - timedelta(days=1)).isoformat()
        },
        {
            "id": "act-005",
            "entity_type": "deal",
            "entity_id": "deal-003",
            "action": "terms_requested",
            "description": "Pepsi Nigeria wants exclusivity clause added to Davido deal. Legal review needed.",
            "metadata": {"status": "warning"},
            "created_at": (now - timedelta(days=1)).isoformat()
        },
        {
            "id": "act-006",
            "entity_type": "deal",
            "entity_id": "deal-014",
            "action": "deal_lost",
            "description": "Globacom deal for Asake fell through. Reason: Budget misalignment. Revenue lost: ₦35M.",
            "metadata": {"status": "error"},
            "created_at": (now - timedelta(days=2)).isoformat()
        },
        {
            "id": "act-007",
            "entity_type": "task",
            "entity_id": "task-003",
            "action": "deliverable_submitted",
            "description": "Creative Kelechi Amadi-Obi submitted deliverables for Cadbury shoot Set 3. Awaiting Don Jazzy team approval.",
            "metadata": {"status": "info"},
            "created_at": (now - timedelta(days=2)).isoformat()
        },
        {
            "id": "act-008",
            "entity_type": "signal",
            "entity_id": "signal-001",
            "action": "market_signal",
            "description": "Flutterwave hiring 'Creator Partnerships Lead' on LinkedIn. Possible deal signal.",
            "metadata": {"status": "info"},
            "created_at": (now - timedelta(days=3)).isoformat()
        }
    ]
    
    # Copilot Recommendations
    copilot_recommendations = [
        {
            "id": "rec-001",
            "type": "deal_signal",
            "title": "Nigerian Breweries - Star Lager Relaunch",
            "description": "Star Lager filed new trademark for 'Star Music Live' on Feb 20. Social media spend increased 340% in 30 days. New CMO appointed from Diageo.",
            "confidence": 92,
            "brand_name": "Nigerian Breweries",
            "estimated_budget": "₦80-120M",
            "recommended_artists": [
                {"name": "Spaceship (Burna Boy)", "match": 96, "reason": "Star's youthful rebrand aligns with 25-34 demo. Previous alcohol brand success with Hennessy."},
                {"name": "Rema Team", "match": 91, "reason": "Gen-Z pull. Viral potential. Star wants younger audience."},
                {"name": "Asake Team", "match": 88, "reason": "Street credibility matches Star's mass-market positioning."}
            ],
            "signal": "Trademark filing + increased ad spend + new CMO",
            "actions": [{"label": "Pursue Deal", "type": "primary"}, {"label": "Dismiss", "type": "secondary"}, {"label": "Save for Later", "type": "ghost"}]
        },
        {
            "id": "rec-002",
            "type": "deal_signal",
            "title": "Access Bank - 10th Anniversary Campaign",
            "description": "Access Bank Q4 earnings call mentioned 'significant marketing spend for anniversary celebration.' PR agency Mediacraft already briefed.",
            "confidence": 87,
            "brand_name": "Access Bank",
            "estimated_budget": "₦50-75M",
            "recommended_artists": [
                {"name": "Mavin Records (Don Jazzy)", "match": 93, "reason": "Business crossover. Already banks with Access. Social media king."},
                {"name": "Leading Vibes (Tems)", "match": 89, "reason": "Global prestige. Access expanding to UK/US markets."}
            ],
            "signal": "Q4 earnings call mention + PR agency briefing",
            "actions": [{"label": "Pursue Deal", "type": "primary"}, {"label": "Dismiss", "type": "secondary"}, {"label": "Save for Later", "type": "ghost"}]
        },
        {
            "id": "rec-003",
            "type": "deal_signal",
            "title": "Flutterwave - Creator Economy Product Launch",
            "description": "Flutterwave hiring 'Creator Partnerships Lead' on LinkedIn. CEO tweeted about creator economy being 'next frontier.'",
            "confidence": 84,
            "brand_name": "Flutterwave",
            "estimated_budget": "₦30-50M",
            "recommended_artists": [
                {"name": "Mavin Talent (Ayra Starr)", "match": 90, "reason": "Rising star narrative matches Flutterwave's growth story."},
                {"name": "YBNL (Olamide)", "match": 87, "reason": "Mass market reach. Business-savvy reputation."}
            ],
            "signal": "LinkedIn hiring + CEO social media activity",
            "actions": [{"label": "Pursue Deal", "type": "primary"}, {"label": "Dismiss", "type": "secondary"}, {"label": "Save for Later", "type": "ghost"}]
        }
    ]
    
    # Messages
    messages = [
        {
            "id": "msg-001",
            "thread_id": "thread-001",
            "sender_id": "staff-001",
            "sender_name": "Tunde Balogun",
            "recipient_id": "brand-002-contact",
            "recipient_name": "Adenike Ogunlesi",
            "content": "Hi Adenike, just sent over the revised contract for the Burna Boy activation. Let me know if legal has any questions.",
            "read": True,
            "created_at": (now - timedelta(hours=4)).isoformat()
        },
        {
            "id": "msg-002",
            "thread_id": "thread-001",
            "sender_id": "brand-002-contact",
            "sender_name": "Adenike Ogunlesi",
            "recipient_id": "staff-001",
            "recipient_name": "Tunde Balogun",
            "content": "Thanks Tunde! Legal is reviewing now. Quick question - can we add a clause about social media exclusivity during the campaign period?",
            "read": True,
            "created_at": (now - timedelta(hours=3)).isoformat()
        },
        {
            "id": "msg-003",
            "thread_id": "thread-001",
            "sender_id": "staff-001",
            "sender_name": "Tunde Balogun",
            "recipient_id": "brand-002-contact",
            "recipient_name": "Adenike Ogunlesi",
            "content": "Absolutely. I'll draft that amendment and send over by EOD. Burna's team is flexible on this.",
            "read": True,
            "created_at": (now - timedelta(hours=2)).isoformat()
        },
        {
            "id": "msg-004",
            "thread_id": "thread-002",
            "sender_id": "sc-001",
            "sender_name": "Mavin Records",
            "recipient_id": "cr-001",
            "recipient_name": "Kelechi Amadi-Obi",
            "content": "Kelechi, the Cadbury Set 2 photos are stunning! Quick note - can we get 3 of them re-cropped to 9:16 for Stories?",
            "read": True,
            "created_at": (now - timedelta(hours=6)).isoformat()
        },
        {
            "id": "msg-005",
            "thread_id": "thread-002",
            "sender_id": "cr-001",
            "sender_name": "Kelechi Amadi-Obi",
            "recipient_id": "sc-001",
            "recipient_name": "Mavin Records",
            "content": "Thank you! Of course. I'll have the re-crops to you by end of day.",
            "read": True,
            "created_at": (now - timedelta(hours=5)).isoformat()
        }
    ]
    
    # Wallet Transactions
    wallet_transactions = [
        {
            "id": "tx-001",
            "user_id": "sc-001",
            "user_name": "Mavin Records",
            "transaction_type": "credit",
            "amount": 3500000,
            "description": "Johnnie Walker Q1 Payment",
            "balance_after": 12450000,
            "created_at": (now - timedelta(days=2)).isoformat()
        },
        {
            "id": "tx-002",
            "user_id": "sc-001",
            "user_name": "Mavin Records",
            "transaction_type": "escrow_hold",
            "amount": 1200000,
            "description": "Concert: Lighting Designer",
            "balance_after": 8950000,
            "created_at": (now - timedelta(days=3)).isoformat()
        },
        {
            "id": "tx-003",
            "user_id": "cr-001",
            "user_name": "Kelechi Amadi-Obi",
            "transaction_type": "credit",
            "amount": 187500,
            "description": "Task approved: Cadbury Set 2",
            "balance_after": 2875000,
            "created_at": (now - timedelta(days=2)).isoformat()
        },
        {
            "id": "tx-004",
            "user_id": "cr-001",
            "user_name": "Kelechi Amadi-Obi",
            "transaction_type": "withdrawal",
            "amount": 1000000,
            "description": "Withdrawal to Zenith Bank ****7892",
            "balance_after": 2687500,
            "created_at": (now - timedelta(days=8)).isoformat()
        }
    ]
    
    # Admin user
    admin = {
        "id": "admin-001",
        "email": "admin@thetasck.com",
        "name": "Platform Admin",
        "role": "admin",
        "location": "Lagos, Nigeria",
        "verified": True
    }
    
    # Brand contacts (for demo login)
    brand_contacts = [
        {
            "id": "brand-contact-001",
            "email": "adenike@diageo-ng.com",
            "name": "Adenike Ogunlesi",
            "role": "brand",
            "brand_id": "brand-002",
            "brand_name": "Guinness Nigeria",
            "title": "Head of Culture and Entertainment",
            "location": "Lagos, Nigeria",
            "verified": True
        }
    ]
    
    return {
        "staff": staff,
        "brands": brands,
        "super_creatives": super_creatives,
        "creatives": creatives,
        "deals": deals,
        "projects": projects,
        "opportunities": opportunities,
        "tasks": tasks,
        "activities": activities,
        "copilot_recommendations": copilot_recommendations,
        "messages": messages,
        "wallet_transactions": wallet_transactions,
        "admin": admin,
        "brand_contacts": brand_contacts
    }
