"""
TASCK OS Seed Data - platform account records only.

The fictional brands and their campaign data (deals, projects, opportunities,
tasks, activities, copilot recommendations, messages and wallet transactions)
have been removed. Brands and their project data are entered by the client
through the CRM, or imported from the CRM workbook by
v3_workbook_import.WorkbookImporter.

What remains are the staff / super-creative / creative / admin / brand-contact
accounts that `/api/auth/demo-login` resolves against the `users` collection.
Without them nobody can sign in to the V1 app.
"""

def get_seed_data():
    """Return the platform account records. No brand or campaign data."""
    
    # TASCK Staff
    staff = [
        {
            "id": "staff-001",
            "email": "tunde@thetasck.com",
            "name": "Tunde Balogun",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Music and Entertainment",
            "artists_managed": ["sc-001", "sc-002", "sc-007", "sc-008"],
            "revenue_ytd": 134500000,
            "bio": "Senior Agent with 8+ years in entertainment management"
        },
        {
            "id": "staff-002",
            "email": "amaka@thetasck.com",
            "name": "Amaka Obi",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Fashion and Lifestyle",
            "artists_managed": ["sc-005", "sc-003", "sc-009"],
            "revenue_ytd": 109200000,
            "bio": "Specializes in fashion and lifestyle brand partnerships"
        },
        {
            "id": "staff-003",
            "email": "femi@thetasck.com",
            "name": "Femi Adeyinka",
            "role": "staff",
            "avatar": None,
            "location": "Abuja, Nigeria",
            "verified": True,
            "focus": "Sports and Brands",
            "artists_managed": ["sc-004", "sc-006"],
            "revenue_ytd": 98700000,
            "bio": "Expert in sports marketing and brand activations"
        },
        {
            "id": "staff-004",
            "email": "nkechi@thetasck.com",
            "name": "Nkechi Eze",
            "role": "staff",
            "avatar": None,
            "location": "Lagos, Nigeria",
            "verified": True,
            "focus": "Emerging Talent",
            "artists_managed": ["sc-010"],
            "revenue_ytd": 42600000,
            "bio": "Scouts and develops emerging Nigerian talent"
        }
    ]
    
    # Super Creatives (Artist Teams)
    super_creatives = [
        {
            "id": "sc-001",
            "email": "team@mavinrecords.com",
            "name": "Mavin Records Team",
            "role": "super_creative",
            "team_name": "Mavin Records",
            "principal_artist": "Don Jazzy",
            "genre": "Producer / Afrobeats",
            "spotify_listeners": "8.4M",
            "instagram_followers": "14.2M",
            "brand_value": "₦350M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 12450000,
            "escrowed": 9000000,
            "verified": True
        },
        {
            "id": "sc-002",
            "email": "team@spaceship.com",
            "name": "Spaceship Team",
            "role": "super_creative",
            "team_name": "Spaceship",
            "principal_artist": "Burna Boy",
            "genre": "Afro-fusion",
            "spotify_listeners": "42.3M",
            "instagram_followers": "12.8M",
            "brand_value": "₦800M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 45000000,
            "escrowed": 15000000,
            "verified": True
        },
        {
            "id": "sc-003",
            "email": "team@dmw.com",
            "name": "DMW Team",
            "role": "super_creative",
            "team_name": "DMW",
            "principal_artist": "Davido",
            "genre": "Afropop",
            "spotify_listeners": "31.2M",
            "instagram_followers": "28.1M",
            "brand_value": "₦750M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 38000000,
            "escrowed": 12000000,
            "verified": True
        },
        {
            "id": "sc-004",
            "email": "team@starboy.com",
            "name": "Starboy Team",
            "role": "super_creative",
            "team_name": "Starboy",
            "principal_artist": "Wizkid",
            "genre": "Afrobeats",
            "spotify_listeners": "38.7M",
            "instagram_followers": "17.4M",
            "brand_value": "₦820M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 52000000,
            "escrowed": 8000000,
            "verified": True
        },
        {
            "id": "sc-005",
            "email": "team@leadingvibes.com",
            "name": "Leading Vibes Team",
            "role": "super_creative",
            "team_name": "Leading Vibes",
            "principal_artist": "Tems",
            "genre": "Alt R&B / Afrobeats",
            "spotify_listeners": "28.9M",
            "instagram_followers": "8.6M",
            "brand_value": "₦500M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 28000000,
            "escrowed": 5000000,
            "verified": True
        },
        {
            "id": "sc-006",
            "email": "team@ybnl.com",
            "name": "YBNL Team",
            "role": "super_creative",
            "team_name": "YBNL",
            "principal_artist": "Olamide",
            "genre": "Yoruba Rap / Afropop",
            "spotify_listeners": "7.1M",
            "instagram_followers": "11.2M",
            "brand_value": "₦250M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 15000000,
            "escrowed": 3000000,
            "verified": True
        },
        {
            "id": "sc-007",
            "email": "team@remateam.com",
            "name": "Rema Team",
            "role": "super_creative",
            "team_name": "Rema Team",
            "principal_artist": "Rema",
            "genre": "Afrorave",
            "spotify_listeners": "45.1M",
            "instagram_followers": "9.2M",
            "brand_value": "₦450M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 32000000,
            "escrowed": 6000000,
            "verified": True
        },
        {
            "id": "sc-008",
            "email": "team@mavintalent.com",
            "name": "Mavin Talent Team",
            "role": "super_creative",
            "team_name": "Mavin Talent",
            "principal_artist": "Ayra Starr",
            "genre": "Afropop",
            "spotify_listeners": "22.3M",
            "instagram_followers": "7.8M",
            "brand_value": "₦280M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 18000000,
            "escrowed": 4000000,
            "verified": True
        },
        {
            "id": "sc-009",
            "email": "team@tiwa.com",
            "name": "Tiwa Savage Team",
            "role": "super_creative",
            "team_name": "Tiwa Savage Team",
            "principal_artist": "Tiwa Savage",
            "genre": "Afrobeats / Pop",
            "spotify_listeners": "12.4M",
            "instagram_followers": "14.1M",
            "brand_value": "₦300M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 22000000,
            "escrowed": 3500000,
            "verified": True
        },
        {
            "id": "sc-010",
            "email": "team@asake.com",
            "name": "Asake Team",
            "role": "super_creative",
            "team_name": "Asake Team",
            "principal_artist": "Asake",
            "genre": "Street-pop",
            "spotify_listeners": "18.2M",
            "instagram_followers": "5.9M",
            "brand_value": "₦320M/yr",
            "location": "Lagos, Nigeria",
            "wallet_balance": 25000000,
            "escrowed": 5000000,
            "verified": True
        }
    ]
    
    # Creatives (Freelancers)
    creatives = [
        {
            "id": "cr-001",
            "email": "kelechi@studio.com",
            "name": "Kelechi Amadi-Obi",
            "role": "creative",
            "skills": ["Photography", "Art Direction", "Editorial"],
            "day_rate": 350000,
            "rating": 4.9,
            "reliability": 97,
            "completed_projects": 14,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2875000,
            "verified": True,
            "tagline": "Award-winning photographer. Editorial and concert specialist.",
            "bio": "With over 15 years of experience, I've worked with Africa's top artists and brands."
        },
        {
            "id": "cr-002",
            "email": "ade@films.com",
            "name": "Ade Adesanya",
            "role": "creative",
            "skills": ["Videography", "Cinematography", "Music Videos"],
            "day_rate": 280000,
            "rating": 4.8,
            "reliability": 91,
            "completed_projects": 11,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1950000,
            "verified": True,
            "tagline": "Director and cinematographer. Music video and brand content.",
            "bio": "Specializing in music videos and brand content that tells compelling stories."
        },
        {
            "id": "cr-003",
            "email": "tolu@design.com",
            "name": "Tolu Akinwande",
            "role": "creative",
            "skills": ["Graphic Design", "Visual Identity", "Campaign Design"],
            "day_rate": 150000,
            "rating": 4.9,
            "reliability": 98,
            "completed_projects": 22,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1250000,
            "verified": True,
            "tagline": "Visual identity and campaign design. Clean, bold aesthetics.",
            "bio": "Creating visual identities that stand out and drive brand recognition."
        },
        {
            "id": "cr-004",
            "email": "chidinma@social.com",
            "name": "Chidinma Okafor",
            "role": "creative",
            "skills": ["Social Media", "Content Strategy", "Community Management"],
            "day_rate": 120000,
            "rating": 4.7,
            "reliability": 94,
            "completed_projects": 18,
            "location": "Lagos, Nigeria",
            "wallet_balance": 980000,
            "verified": True,
            "tagline": "Social strategy and content management. 500M+ impressions managed.",
            "bio": "Helping brands connect with their audience through strategic social content."
        },
        {
            "id": "cr-005",
            "email": "seun@stages.com",
            "name": "Seun Ogunlesi",
            "role": "creative",
            "skills": ["Stage Design", "Event Production", "Immersive Experiences"],
            "day_rate": 400000,
            "rating": 5.0,
            "reliability": 100,
            "completed_projects": 7,
            "location": "Lagos, Nigeria",
            "wallet_balance": 3500000,
            "verified": True,
            "tagline": "Immersive stage experiences. Concerts and corporate events.",
            "bio": "Designing unforgettable stage experiences for Africa's biggest concerts."
        },
        {
            "id": "cr-006",
            "email": "simi@sound.com",
            "name": "Simi Oluwadare",
            "role": "creative",
            "skills": ["Sound Engineering", "Live Sound", "Studio Mixing"],
            "day_rate": 250000,
            "rating": 4.8,
            "reliability": 95,
            "completed_projects": 9,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1800000,
            "verified": True,
            "tagline": "Live sound and studio mixing. Major festival experience.",
            "bio": "Delivering crystal-clear sound for live events and studio recordings."
        },
        {
            "id": "cr-007",
            "email": "funke@styling.com",
            "name": "Funke Adeyemi",
            "role": "creative",
            "skills": ["Styling", "Fashion", "Celebrity Wardrobe"],
            "day_rate": 200000,
            "rating": 4.9,
            "reliability": 96,
            "completed_projects": 16,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2100000,
            "verified": True,
            "tagline": "Celebrity and editorial styling. Worked with top Nollywood talent.",
            "bio": "Styling Africa's biggest stars for red carpets and campaigns."
        },
        {
            "id": "cr-008",
            "email": "emeka@motion.com",
            "name": "Emeka Nwosu",
            "role": "creative",
            "skills": ["Motion Graphics", "Animation", "After Effects"],
            "day_rate": 180000,
            "rating": 4.7,
            "reliability": 92,
            "completed_projects": 13,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1450000,
            "verified": True,
            "tagline": "After Effects and Cinema 4D specialist. Brand animations.",
            "bio": "Bringing brands to life through dynamic motion graphics."
        },
        {
            "id": "cr-009",
            "email": "yemi@copy.com",
            "name": "Yemi Adebayo",
            "role": "creative",
            "skills": ["Copywriting", "Brand Voice", "Campaign Copy"],
            "day_rate": 100000,
            "rating": 4.8,
            "reliability": 97,
            "completed_projects": 25,
            "location": "Lagos, Nigeria",
            "wallet_balance": 850000,
            "verified": True,
            "tagline": "Brand voice and campaign copy. Bilingual English/Yoruba.",
            "bio": "Crafting words that resonate with Nigerian audiences."
        },
        {
            "id": "cr-010",
            "email": "bola@pr.com",
            "name": "Bola Okonkwo",
            "role": "creative",
            "skills": ["PR", "Media Relations", "Press Coverage"],
            "day_rate": 300000,
            "rating": 4.6,
            "reliability": 90,
            "completed_projects": 8,
            "location": "Abuja, Nigeria",
            "wallet_balance": 2200000,
            "verified": True,
            "tagline": "Media relations and press coverage. Government and entertainment.",
            "bio": "Connecting brands with media outlets across Nigeria."
        },
        {
            "id": "cr-011",
            "email": "ngozi@makeup.com",
            "name": "Ngozi Okafor",
            "role": "creative",
            "skills": ["Makeup Artistry", "Editorial Makeup", "Film"],
            "day_rate": 150000,
            "rating": 5.0,
            "reliability": 99,
            "completed_projects": 20,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1650000,
            "verified": True,
            "tagline": "Editorial and film makeup. Natural beauty specialist.",
            "bio": "Enhancing natural beauty for editorial and film productions."
        },
        {
            "id": "cr-012",
            "email": "ibrahim@beats.com",
            "name": "Ibrahim Hassan",
            "role": "creative",
            "skills": ["Music Production", "Beat Making", "Afrobeats"],
            "day_rate": 200000,
            "rating": 4.8,
            "reliability": 93,
            "completed_projects": 12,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1350000,
            "verified": True,
            "tagline": "Beat maker and producer. Afrobeats and amapiano.",
            "bio": "Creating the sounds that define Nigerian music."
        },
        {
            "id": "cr-013",
            "email": "amara@content.com",
            "name": "Amara Eze",
            "role": "creative",
            "skills": ["Content Writing", "Blog Posts", "Brand Storytelling"],
            "day_rate": 80000,
            "rating": 4.9,
            "reliability": 98,
            "completed_projects": 30,
            "location": "Lagos, Nigeria",
            "wallet_balance": 720000,
            "verified": True,
            "tagline": "Blog posts, press releases, brand storytelling.",
            "bio": "Telling brand stories that connect and convert."
        },
        {
            "id": "cr-014",
            "email": "dayo@events.com",
            "name": "Dayo Olatunji",
            "role": "creative",
            "skills": ["Event Planning", "Logistics", "Large-scale Events"],
            "day_rate": 350000,
            "rating": 4.7,
            "reliability": 94,
            "completed_projects": 6,
            "location": "Lagos, Nigeria",
            "wallet_balance": 2800000,
            "verified": True,
            "tagline": "Large-scale events. 500+ capacity. Logistics specialist.",
            "bio": "Orchestrating flawless events for thousands of attendees."
        },
        {
            "id": "cr-015",
            "email": "zainab@uiux.com",
            "name": "Zainab Mohammed",
            "role": "creative",
            "skills": ["UI/UX Design", "App Design", "Prototyping"],
            "day_rate": 200000,
            "rating": 4.8,
            "reliability": 95,
            "completed_projects": 15,
            "location": "Abuja, Nigeria",
            "wallet_balance": 1900000,
            "verified": True,
            "tagline": "App and web design. User research and prototyping.",
            "bio": "Designing digital experiences that users love."
        },
        {
            "id": "cr-016",
            "email": "chukwu@edit.com",
            "name": "Chukwuemeka Obi",
            "role": "creative",
            "skills": ["Video Editing", "Social Cutdowns", "Long-form"],
            "day_rate": 160000,
            "rating": 4.7,
            "reliability": 93,
            "completed_projects": 19,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1100000,
            "verified": True,
            "tagline": "Fast turnaround editor. Social cutdowns and long-form.",
            "bio": "Editing content that performs across all platforms."
        },
        {
            "id": "cr-017",
            "email": "aisha@photos.com",
            "name": "Aisha Bello",
            "role": "creative",
            "skills": ["Photography", "Portrait", "Corporate"],
            "day_rate": 250000,
            "rating": 4.8,
            "reliability": 96,
            "completed_projects": 10,
            "location": "Abuja, Nigeria",
            "wallet_balance": 1750000,
            "verified": True,
            "tagline": "Portrait and corporate photography. Clean and professional.",
            "bio": "Capturing professional moments for corporate clients."
        },
        {
            "id": "cr-018",
            "email": "olumide@creative.com",
            "name": "Olumide Bakare",
            "role": "creative",
            "skills": ["Creative Direction", "Campaign Lead", "Concept"],
            "day_rate": 400000,
            "rating": 4.9,
            "reliability": 97,
            "completed_projects": 8,
            "location": "Lagos, Nigeria",
            "wallet_balance": 3200000,
            "verified": True,
            "tagline": "Campaign creative lead. Concept to execution.",
            "bio": "Leading creative campaigns from concept to execution."
        },
        {
            "id": "cr-019",
            "email": "blessing@scripts.com",
            "name": "Blessing Nwachukwu",
            "role": "creative",
            "skills": ["Scriptwriting", "TVC Scripts", "Documentary"],
            "day_rate": 120000,
            "rating": 4.6,
            "reliability": 91,
            "completed_projects": 14,
            "location": "Lagos, Nigeria",
            "wallet_balance": 920000,
            "verified": True,
            "tagline": "TVC scripts, brand films, documentary.",
            "bio": "Writing scripts that bring brand stories to life."
        },
        {
            "id": "cr-020",
            "email": "tunde@sounddesign.com",
            "name": "Tunde Oyelola",
            "role": "creative",
            "skills": ["Sound Design", "Foley", "Mixing"],
            "day_rate": 180000,
            "rating": 4.7,
            "reliability": 92,
            "completed_projects": 11,
            "location": "Lagos, Nigeria",
            "wallet_balance": 1380000,
            "verified": True,
            "tagline": "Sound design for film and ads. Foley and mixing.",
            "bio": "Creating immersive soundscapes for visual content."
        }
    ]
    
    # Admin user
    admin = {
        "id": "admin-001",
        "email": "admin@thetasck.com",
        "name": "Platform Admin",
        "role": "admin",
        "location": "Lagos, Nigeria",
        "verified": True
    }
    
    # Brand contacts (for demo login)
    brand_contacts = [
        {
            "id": "brand-contact-001",
            "email": "adenike@diageo-ng.com",
            "name": "Adenike Ogunlesi",
            "role": "brand",
            "brand_id": "brand-002",
            "brand_name": "Guinness Nigeria",
            "title": "Head of Culture and Entertainment",
            "location": "Lagos, Nigeria",
            "verified": True
        }
    ]
    
    return {
        "staff": staff,
        "super_creatives": super_creatives,
        "creatives": creatives,
        "admin": admin,
        "brand_contacts": brand_contacts
    }
