// TASCK on Azure - resource group scoped deployment.
//
// Creates everything TASCK needs in one dedicated resource group:
//   Log Analytics + Application Insights   observability
//   Azure Container Registry               API and web images (linux/amd64)
//   Key Vault                              every secret; apps read via managed identity
//   User-assigned managed identity         ACR pull + Key Vault secret read for the apps
//   Cosmos DB for MongoDB (vCore)          NEW, EMPTY database (production data is restored
//                                          later, as a separate controlled phase)
//   Container Apps environment             hosts the API and web container apps
//   Container App: tasck-api               FastAPI, internal ingress only
//   Container App: tasck-web               nginx + React build, external ingress, proxies /api
//
// Deploy with infra/deploy.sh (it also builds the images and wires the FQDNs).

targetScope = 'resourceGroup'

@description('Azure region for every resource.')
param location string = resourceGroup().location

@description('Short environment label used in resource names, e.g. prod, staging.')
@minLength(2)
@maxLength(10)
param envName string = 'prod'

@description('Cosmos DB for MongoDB vCore administrator user name.')
param mongoAdminUser string = 'tasckadmin'

@secure()
@description('Cosmos DB for MongoDB vCore administrator password (generated by deploy.sh, stored in Key Vault).')
param mongoAdminPassword string

@description('Mongo vCore compute tier. M10 is the smallest paid tier; raise before restoring production data if needed.')
@allowed(['Free', 'M10', 'M20', 'M25', 'M30', 'M40', 'M50', 'M60', 'M80'])
param mongoTier string = 'M10'

@description('Mongo vCore storage in GiB (32 minimum for M10+).')
param mongoStorageGb int = 32

@description('MongoDB server version for the vCore cluster.')
@allowed(['7.0', '8.0'])
param mongoServerVersion string = '8.0'

@description('Database name the API uses (DB_NAME). New and empty at first deploy.')
param dbName string = 'tasck'

@description('API container image. Defaults to a placeholder until deploy.sh builds the real one.')
param apiImage string = 'mcr.microsoft.com/k8se/quickstart:latest'

@description('Web container image. Defaults to a placeholder until deploy.sh builds the real one.')
param webImage string = 'mcr.microsoft.com/k8se/quickstart:latest'

@description('Port the API container listens on (matches Dockerfile.api PORT).')
param apiPort int = 8000

@description('Port the web container listens on (nginx-unprivileged).')
param webPort int = 8080

@description('Extra public origins allowed by the API CORS policy (comma-separated). The web app origin is added automatically.')
param extraCorsOrigins string = ''

@description('Public URL the API should use in emails and portal links. Defaults to the web app FQDN.')
param publicAppUrl string = ''

@description('Keep the passwordless role login (current production behaviour). Set false once a credentialed admin login exists.')
param enableDemoLogin bool = true

@description('Object id of the operator running the deployment; granted Key Vault Secrets Officer so deploy.sh can write secrets.')
param deployerObjectId string = ''

@description('Set true only after the real secrets exist in Key Vault; before that the API app would fail to start on missing secret references.')
param wireApiSecrets bool = false

@description('Create the two container apps. deploy.sh runs once with false (registry, vault, database, environment), builds the images, then again with true.')
param deployApps bool = true

// --- Non-secret SMTP settings (the password and username are Key Vault secrets) ---
param smtpHost string = ''
param smtpPort string = '587'
param smtpFromEmail string = ''
param smtpFromName string = 'TASCK'
param smtpReplyTo string = ''
param smtpUseTls string = 'true'
param smtpUseSsl string = 'false'

// --- Restore / cutover preparation ---
@description('Operator public IP allowed to reach the Mongo cluster directly (mongorestore/mongosh from a workstation). Empty = Azure services only.')
param operatorIp string = ''

@description('Custom production hostname for the web app (e.g. app.example.com). Empty = not configured. The DNS records printed in the outputs must exist BEFORE deploying with this set.')
param customDomain string = ''

@description('Managed-certificate validation method. Use HTTP for an apex/A-record domain and CNAME for a subdomain.')
@allowed([
  'CNAME'
  'HTTP'
  'TXT'
])
param customDomainValidationMethod string = 'CNAME'

@description('Resource id of the managed certificate for customDomain. Empty on the first pass (domain bound without TLS while the certificate is issued); deploy.sh feeds the id on the second pass.')
param customDomainCertificateId string = ''

// --- AI model / timeout settings (non-secret) ---
@description('Default Claude model for every AI feature (ALIGNMENT_ANALYZER_MODEL; per-feature *_LLM_MODEL fall back to it).')
param aiModel string = 'claude-sonnet-4-5'
param alignmentAnalyzerTimeoutSeconds string = '75'
param analyzeAllHardTimeoutSeconds string = '35'
param creatorMatchTimeoutSeconds string = '50'

var suffix = toLower(take(uniqueString(resourceGroup().id), 8))
var tags = {
  project: 'tasck'
  environment: envName
  managedBy: 'bicep'
}

// ---------------------------------------------------------------------------
// Observability
// ---------------------------------------------------------------------------
resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: 'log-tasck-${envName}'
  location: location
  tags: tags
  properties: {
    sku: { name: 'PerGB2018' }
    retentionInDays: 30
    features: { enableLogAccessUsingOnlyResourcePermissions: true }
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: 'appi-tasck-${envName}'
  location: location
  tags: tags
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
    IngestionMode: 'LogAnalytics'
  }
}

// ---------------------------------------------------------------------------
// Identity, registry, key vault
// ---------------------------------------------------------------------------
resource identity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: 'id-tasck-${envName}'
  location: location
  tags: tags
}

resource acr 'Microsoft.ContainerRegistry/registries@2023-11-01-preview' = {
  name: 'acrtasck${envName}${suffix}'
  location: location
  tags: tags
  sku: { name: 'Basic' }
  properties: {
    adminUserEnabled: false
    publicNetworkAccess: 'Enabled'
  }
}

// AcrPull for the apps' identity.
resource acrPull 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(acr.id, identity.id, 'acrpull')
  scope: acr
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '7f951dda-4ed3-4680-a7ca-43fe172d538d')
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

var keyVaultName = 'kv-tasck-${envName}-${suffix}'
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  tags: tags
  properties: {
    tenantId: subscription().tenantId
    sku: { family: 'A', name: 'standard' }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    publicNetworkAccess: 'Enabled'
  }
}

// Key Vault Secrets User for the apps' identity.
resource kvSecretsUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, identity.id, 'kv-secrets-user')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
    principalId: identity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// Key Vault Secrets Officer for the operator so deploy.sh can write secrets.
resource kvSecretsOfficer 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(deployerObjectId)) {
  name: guid(keyVault.id, deployerObjectId, 'kv-secrets-officer')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7')
    principalId: deployerObjectId
    principalType: 'User'
  }
}

// ---------------------------------------------------------------------------
// MongoDB (Cosmos DB for MongoDB vCore) - new, empty
// ---------------------------------------------------------------------------
resource mongo 'Microsoft.DocumentDB/mongoClusters@2025-09-01' = {
  name: 'mongo-tasck-${envName}-${suffix}'
  location: location
  tags: tags
  properties: {
    administrator: {
      userName: mongoAdminUser
      password: mongoAdminPassword
    }
    serverVersion: mongoServerVersion
    compute: { tier: mongoTier }
    storage: { sizeGb: mongoStorageGb }
    sharding: { shardCount: 1 }
    highAvailability: { targetMode: 'Disabled' }
    publicNetworkAccess: 'Enabled'
  }
}

// Allow Azure-hosted services (the Container Apps environment) to reach the cluster.
resource mongoAllowAzure 'Microsoft.DocumentDB/mongoClusters/firewallRules@2025-09-01' = {
  parent: mongo
  name: 'AllowAllAzureServicesAndResourcesWithinAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource mongoAllowOperator 'Microsoft.DocumentDB/mongoClusters/firewallRules@2025-09-01' = if (!empty(operatorIp)) {
  parent: mongo
  name: 'AllowOperatorWorkstation'
  properties: {
    startIpAddress: operatorIp
    endIpAddress: operatorIp
  }
}

// ---------------------------------------------------------------------------
// Restore staging: an Azure Files share mounted into the restore/inventory jobs.
// The production mongodump archive is uploaded here; nothing else uses it.
// ---------------------------------------------------------------------------
resource restoreStorage 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: 'sttasck${envName}${suffix}'
  location: location
  tags: tags
  sku: { name: 'Standard_LRS' }
  kind: 'StorageV2'
  properties: {
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    supportsHttpsTrafficOnly: true
  }
}

resource restoreFileService 'Microsoft.Storage/storageAccounts/fileServices@2023-05-01' = {
  parent: restoreStorage
  name: 'default'
}

resource restoreShare 'Microsoft.Storage/storageAccounts/fileServices/shares@2023-05-01' = {
  parent: restoreFileService
  name: 'restore'
  properties: { shareQuota: 100 }
}

// The service returns the SRV connection string with <user>/<password> placeholders.
var mongoConnectionString = replace(replace(mongo.properties.connectionString, '<user>', mongoAdminUser), '<password>', uriComponent(mongoAdminPassword))

resource secretMongoUrl 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'mongo-url'
  properties: { value: mongoConnectionString, contentType: 'MongoDB SRV connection string (vCore)' }
}

resource secretMongoAdminPassword 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'mongo-admin-password'
  properties: { value: mongoAdminPassword, contentType: 'Mongo vCore administrator password' }
}

// ---------------------------------------------------------------------------
// Container Apps
// ---------------------------------------------------------------------------
resource containerEnv 'Microsoft.App/managedEnvironments@2025-01-01' = {
  name: 'cae-tasck-${envName}'
  location: location
  tags: tags
  properties: {
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
    daprAIConnectionString: appInsights.properties.ConnectionString
    zoneRedundant: false
    workloadProfiles: [
      { name: 'Consumption', workloadProfileType: 'Consumption' }
    ]
  }
}

resource restoreEnvStorage 'Microsoft.App/managedEnvironments/storages@2025-01-01' = {
  parent: containerEnv
  name: 'restore'
  properties: {
    azureFile: {
      accountName: restoreStorage.name
      accountKey: restoreStorage.listKeys().keys[0].value
      shareName: restoreShare.name
      accessMode: 'ReadWrite'
    }
  }
}

// Manual job: restores a mongodump archive from the share into the vCore cluster.
// Started by infra/restore-production.sh, never automatically.
resource restoreJob 'Microsoft.App/jobs@2025-01-01' = {
  name: 'tasck-restore'
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [kvSecretsUser, secretMongoUrl]
  properties: {
    environmentId: containerEnv.id
    workloadProfileName: 'Consumption'
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 14400
      replicaRetryLimit: 0
      manualTriggerConfig: { parallelism: 1, replicaCompletionCount: 1 }
      secrets: [
        { name: 'mongo-url', keyVaultUrl: '${keyVaultUri}secrets/mongo-url', identity: identity.id }
      ]
    }
    template: {
      containers: [
        {
          name: 'mongorestore'
          image: 'mongo:8.0'
          command: ['/bin/bash', '-c']
          // DUMP_FILE / SOURCE_DB / TARGET_DB / DROP / MODE are set with `az containerapp job update --set-env-vars` before each start
          // (a start-time template override would drop the share mount).
          args: [
            'set -euo pipefail; f=/restore/$DUMP_FILE; if [ "$MODE" = "dump" ]; then echo "dumping $SOURCE_DB -> $f"; mongodump --uri "$MONGO_URL" --db "$SOURCE_DB" --archive="$f" --gzip; ls -la "$f"; echo "dump finished"; exit 0; fi; test -f "$f" || { echo "missing $f"; ls -la /restore; exit 1; }; case "$f" in *.gz) gz="--gzip" ;; *) gz="" ;; esac; if [ "$MODE" = "dryrun" ]; then echo "dry run of $f (no writes): namespaces for $SOURCE_DB"; mongorestore --uri "$MONGO_URL" --archive="$f" $gz --nsInclude "$SOURCE_DB.*" --nsFrom "$SOURCE_DB.*" --nsTo "$TARGET_DB.*" --dryRun -vv 2>&1 | grep -Ei "found collection|restoring|namespace|error|failed" | head -200; echo "dry run finished"; exit 0; fi; echo "restoring $f: $SOURCE_DB -> $TARGET_DB (drop=$DROP)"; extra=""; [ "$DROP" = "true" ] && extra="--drop"; mongorestore --uri "$MONGO_URL" --archive="$f" $gz --nsFrom "$SOURCE_DB.*" --nsTo "$TARGET_DB.*" --nsInclude "$SOURCE_DB.*" --maintainInsertionOrder --numParallelCollections 2 --numInsertionWorkersPerCollection 2 $extra; echo "restore finished"'
          ]
          env: [
            { name: 'MONGO_URL', secretRef: 'mongo-url' }
            { name: 'DUMP_FILE', value: 'production.archive.gz' }
            { name: 'SOURCE_DB', value: 'test_database' }
            { name: 'TARGET_DB', value: dbName }
            { name: 'DROP', value: 'false' }
            { name: 'MODE', value: 'restore' } // restore | dump | dryrun (dump: mongodump SOURCE_DB into DUMP_FILE; dryrun: validate the archive, list namespaces, write nothing)
          ]
          resources: { cpu: json('1.0'), memory: '2Gi' }
          volumeMounts: [ { volumeName: 'restore', mountPath: '/restore' } ]
        }
      ]
      volumes: [
        { name: 'restore', storageType: 'AzureFile', storageName: restoreEnvStorage.name }
      ]
    }
  }
}

// Manual job: read-only inventory of the target database, written to the share
// as target-inventory.json for backend/verify_restore.py.
resource inventoryJob 'Microsoft.App/jobs@2025-01-01' = if (deployApps) {
  name: 'tasck-inventory'
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull, kvSecretsUser, secretMongoUrl]
  properties: {
    environmentId: containerEnv.id
    workloadProfileName: 'Consumption'
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 7200
      replicaRetryLimit: 0
      manualTriggerConfig: { parallelism: 1, replicaCompletionCount: 1 }
      registries: [ { server: acr.properties.loginServer, identity: identity.id } ]
      secrets: [
        { name: 'mongo-url', keyVaultUrl: '${keyVaultUri}secrets/mongo-url', identity: identity.id }
      ]
    }
    template: {
      containers: [
        {
          name: 'inventory'
          image: apiImage
          command: ['python', 'inventory_mongo.py', '--uri-env', 'MONGO_URL', '--db-env', 'DB_NAME', '--out', '/restore/target-inventory.json']
          env: [
            { name: 'MONGO_URL', secretRef: 'mongo-url' }
            { name: 'DB_NAME', value: dbName }
          ]
          resources: { cpu: json('0.5'), memory: '1Gi' }
          volumeMounts: [ { volumeName: 'restore', mountPath: '/restore' } ]
        }
      ]
      volumes: [
        { name: 'restore', storageType: 'AzureFile', storageName: restoreEnvStorage.name }
      ]
    }
  }
}

// Managed TLS certificate for the custom domain. Created once the domain is bound
// (first pass, bindingType Disabled) and the DNS validation records exist.
resource webManagedCert 'Microsoft.App/managedEnvironments/managedCertificates@2025-01-01' = if (!empty(customDomain) && empty(customDomainCertificateId)) {
  parent: containerEnv
  name: 'cert-${replace(customDomain, '.', '-')}'
  location: location
  tags: tags
  properties: {
    subjectName: customDomain
    domainControlValidation: customDomainValidationMethod
  }
  dependsOn: [webApp]
}

// Availability test: the public health endpoint every 5 minutes from three regions.
resource healthWebTest 'Microsoft.Insights/webtests@2022-06-15' = if (deployApps) {
  name: 'tasck-web-health'
  location: location
  tags: union(tags, { 'hidden-link:${appInsights.id}': 'Resource' })
  kind: 'standard'
  properties: {
    SyntheticMonitorId: 'tasck-web-health'
    Name: 'TASCK web /api/health'
    Enabled: true
    Frequency: 300
    Timeout: 30
    Kind: 'standard'
    RetryEnabled: true
    Locations: [
      { Id: 'emea-nl-ams-azr' }
      { Id: 'emea-gb-db3-azr' }
      { Id: 'emea-fr-pra-edge' }
    ]
    Request: {
      RequestUrl: 'https://${webFqdn}/api/health'
      HttpVerb: 'GET'
      ParseDependentRequests: false
    }
    ValidationRules: {
      ExpectedHttpStatusCode: 200
      SSLCheck: true
      SSLCertRemainingLifetimeCheck: 7
    }
  }
}

var webFqdn = 'tasck-web.${containerEnv.properties.defaultDomain}'
var apiInternalFqdn = 'tasck-api.internal.${containerEnv.properties.defaultDomain}'
var effectivePublicAppUrl = empty(publicAppUrl) ? 'https://${webFqdn}' : publicAppUrl
var corsOrigins = empty(extraCorsOrigins) ? 'https://${webFqdn}' : 'https://${webFqdn},${extraCorsOrigins}'

// Secret names the API expects in Key Vault. deploy.sh writes the values; the
// mongo-url secret is written by this template.
var apiSecretNames = wireApiSecrets ? [
  'mongo-url'
  'anthropic-api-key'
  'serpapi-api-key'
  'smtp-username'
  'smtp-password'
] : [
  'mongo-url'
]
// Built from the vault NAME (known at deployment start) rather than
// keyVault.properties.vaultUri, which a for-body may not reference.
var keyVaultUri = 'https://${keyVaultName}${environment().suffixes.keyvaultDns}/'
var apiSecrets = [for s in apiSecretNames: {
  name: s
  keyVaultUrl: '${keyVaultUri}secrets/${s}'
  identity: identity.id
}]

resource apiApp 'Microsoft.App/containerApps@2025-01-01' = if (deployApps) {
  name: 'tasck-api'
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull, kvSecretsUser, secretMongoUrl]
  properties: {
    managedEnvironmentId: containerEnv.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: false // reached only through the web tier's /api proxy
        targetPort: apiPort
        transport: 'http'
        allowInsecure: false
      }
      registries: [
        { server: acr.properties.loginServer, identity: identity.id }
      ]
      secrets: apiSecrets
    }
    template: {
      containers: [
        {
          name: 'api'
          image: apiImage
          resources: { cpu: json('1.0'), memory: '2Gi' }
          env: concat([
            { name: 'APP_ENV', value: 'production' }
            { name: 'PORT', value: string(apiPort) }
            { name: 'DB_NAME', value: dbName }
            { name: 'MONGO_URL', secretRef: 'mongo-url' }
            { name: 'CORS_ORIGINS', value: corsOrigins }
            { name: 'FRONTEND_URL', value: effectivePublicAppUrl }
            { name: 'PUBLIC_APP_URL', value: effectivePublicAppUrl }
            { name: 'APP_BASE_URL', value: effectivePublicAppUrl }
            { name: 'DEFAULT_PUBLIC_APP_URL', value: effectivePublicAppUrl }
            { name: 'BRAND_PORTAL_URL', value: '${effectivePublicAppUrl}/brand/login' }
            { name: 'CREATOR_PORTAL_URL', value: '${effectivePublicAppUrl}/creator/login' }
            { name: 'ENABLE_DEMO_LOGIN', value: enableDemoLogin ? 'true' : 'false' }
            { name: 'ENABLE_DEMO_BOOTSTRAP', value: 'false' }
            { name: 'ENABLE_DIAGNOSTICS', value: 'false' }
            { name: 'ENABLE_ADMIN_CLEANUP', value: 'false' }
            { name: 'TASCK_AI_PROVIDER', value: 'anthropic' }
            { name: 'ALIGNMENT_ANALYZER_MODEL', value: aiModel }
            { name: 'BRAND_ABOUT_LLM_MODEL', value: aiModel }
            { name: 'BRAINSTORM_LLM_MODEL', value: aiModel }
            { name: 'CREATOR_MATCH_LLM_MODEL', value: aiModel }
            { name: 'ALIGNMENT_ANALYZER_TIMEOUT_SECONDS', value: alignmentAnalyzerTimeoutSeconds }
            { name: 'ANALYZE_ALL_HARD_TIMEOUT_SECONDS', value: analyzeAllHardTimeoutSeconds }
            { name: 'CREATOR_MATCH_TIMEOUT_SECONDS', value: creatorMatchTimeoutSeconds }
            { name: 'SMTP_HOST', value: smtpHost }
            { name: 'SMTP_PORT', value: smtpPort }
            { name: 'SMTP_FROM_EMAIL', value: smtpFromEmail }
            { name: 'SMTP_FROM_NAME', value: smtpFromName }
            { name: 'SMTP_REPLY_TO', value: smtpReplyTo }
            { name: 'SMTP_USE_TLS', value: smtpUseTls }
            { name: 'SMTP_USE_SSL', value: smtpUseSsl }
            { name: 'APPLICATIONINSIGHTS_CONNECTION_STRING', value: appInsights.properties.ConnectionString }
          ], wireApiSecrets ? [
            { name: 'ANTHROPIC_API_KEY', secretRef: 'anthropic-api-key' }
            { name: 'SERPAPI_API_KEY', secretRef: 'serpapi-api-key' }
            { name: 'SMTP_USERNAME', secretRef: 'smtp-username' }
            { name: 'SMTP_PASSWORD', secretRef: 'smtp-password' }
          ] : [])
          probes: [
            {
              type: 'Startup'
              httpGet: { path: '/api/health', port: apiPort }
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 24
            }
            {
              type: 'Liveness'
              httpGet: { path: '/api/health', port: apiPort }
              periodSeconds: 30
              failureThreshold: 3
            }
            {
              type: 'Readiness'
              httpGet: { path: '/api/health', port: apiPort }
              periodSeconds: 10
              failureThreshold: 3
            }
          ]
        }
      ]
      // One replica: long-running AI/document jobs run in-process. Scale out
      // only after moving jobs to a durable queue.
      scale: { minReplicas: 1, maxReplicas: 1 }
    }
  }
}

resource webApp 'Microsoft.App/containerApps@2025-01-01' = if (deployApps) {
  name: 'tasck-web'
  location: location
  tags: tags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: { '${identity.id}': {} }
  }
  dependsOn: [acrPull]
  properties: {
    managedEnvironmentId: containerEnv.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: webPort
        transport: 'auto'
        allowInsecure: false
        customDomains: empty(customDomain) ? null : [
          {
            name: customDomain
            bindingType: empty(customDomainCertificateId) ? 'Disabled' : 'SniEnabled'
            certificateId: empty(customDomainCertificateId) ? null : customDomainCertificateId
          }
        ]
      }
      registries: [
        { server: acr.properties.loginServer, identity: identity.id }
      ]
    }
    template: {
      containers: [
        {
          name: 'web'
          image: webImage
          resources: { cpu: json('0.5'), memory: '1Gi' }
          env: [
            { name: 'API_UPSTREAM', value: 'https://${apiInternalFqdn}' }
          ]
          probes: [
            {
              type: 'Liveness'
              httpGet: { path: '/healthz', port: webPort }
              periodSeconds: 30
            }
            {
              type: 'Readiness'
              httpGet: { path: '/healthz', port: webPort }
              periodSeconds: 10
            }
          ]
        }
      ]
      scale: { minReplicas: 1, maxReplicas: 2 }
    }
  }
}

// ---------------------------------------------------------------------------
// Outputs consumed by deploy.sh
// ---------------------------------------------------------------------------
output resourceGroupName string = resourceGroup().name
output acrName string = acr.name
output acrLoginServer string = acr.properties.loginServer
output keyVaultName string = keyVault.name
output keyVaultUri string = keyVault.properties.vaultUri
output identityName string = identity.name
output containerEnvName string = containerEnv.name
output containerEnvDefaultDomain string = containerEnv.properties.defaultDomain
output webFqdn string = webFqdn
output apiInternalFqdn string = apiInternalFqdn
output mongoClusterName string = mongo.name
output mongoHost string = '${mongo.name}.mongocluster.cosmos.azure.com'
output dbName string = dbName
output appInsightsName string = appInsights.name
output restoreStorageAccount string = restoreStorage.name
output restoreShareName string = restoreShare.name
output restoreJobName string = restoreJob.name
output customDomainVerificationId string = containerEnv.properties.customDomainConfiguration.customDomainVerificationId
output containerEnvStaticIp string = containerEnv.properties.staticIp
output customDomainCertificateId string = (!empty(customDomain) && empty(customDomainCertificateId)) ? webManagedCert.id : customDomainCertificateId
output logAnalyticsName string = logAnalytics.name
