export const demoOpportunityCandidates = [
  {
    id: 'oppcand-demo-coke-campus',
    scan_id: 'oppscan-demo',
    brand_name: 'Coca-Cola Nigeria Limited',
    country: 'Nigeria',
    industry: 'FMCG / Beverages',
    campaign_name: 'Campus Share Moments',
    campaign_type: 'creator campaign',
    pain_point: 'Student culture and campus event content is moving fast, but beverage brands are not owning the moment with a measurable creator-led mechanic.',
    suggested_opportunity_angle: 'Prepare an Alignment Snapshot around campus storytelling, personalized sharing moments, and retail-to-social UGC.',
    source_url: 'https://www.coca-cola.com/ng/en/media-center',
    source_title: 'Coca-Cola Nigeria campaign activity',
    source_snippet: 'Public campaign and culture activity signals useful for a creator-led campus opportunity.',
    detected_keywords: ['campaign', 'Nigeria', 'brand', 'creator'],
    confidence_score: 94,
    status: 'pending',
    created_at: '2026-05-26T06:00:00.000Z',
  },
  {
    id: 'oppcand-demo-mtn-data',
    scan_id: 'oppscan-demo',
    brand_name: 'MTN Nigeria Communications PLC',
    country: 'Nigeria',
    industry: 'Telecommunications',
    campaign_name: 'Data For Creators Push',
    campaign_type: 'marketing campaign',
    pain_point: 'Creator economy conversations show high data spend as a barrier to consistent posting, especially among students and micro-influencers.',
    suggested_opportunity_angle: 'Position MTN as the network powering the next wave of Nigerian creators with a creator challenge and data-led conversion KPI.',
    source_url: 'https://www.mtn.ng/news/',
    source_title: 'MTN Nigeria marketing and creator economy signals',
    source_snippet: 'Public web signals connect telco data products with creator and youth culture conversations.',
    detected_keywords: ['campaign', 'Nigeria', 'creator', 'marketing'],
    confidence_score: 91,
    status: 'pending',
    created_at: '2026-05-26T06:00:00.000Z',
  },
  {
    id: 'oppcand-demo-star-nightlife',
    scan_id: 'oppscan-demo',
    brand_name: 'Nigerian Breweries PLC (Star Lager)',
    country: 'Nigeria',
    industry: 'FMCG / Beverages',
    campaign_name: 'Nightlife Reboot',
    campaign_type: 'advertising',
    pain_point: 'Lagos nightlife content is fragmented across TikTok, Instagram, event pages, and entertainment blogs, creating a gap for cleaner cultural ownership.',
    suggested_opportunity_angle: 'Build a Star-led nightlife content system with approved venues, creators, responsible-drinking controls, and measurable event attendance lift.',
    source_url: 'https://www.nbplc.com/brands/star-lager',
    source_title: 'Star Lager brand and nightlife positioning',
    source_snippet: 'Public nightlife and brand signals indicate a possible creator-led campaign opening.',
    detected_keywords: ['advertising', 'Nigeria', 'brand'],
    confidence_score: 88,
    status: 'rejected',
    reviewed_at: '2026-05-26T06:05:00.000Z',
    reviewed_by: 'admin',
    created_at: '2026-05-26T06:00:00.000Z',
  },
  {
    id: 'oppcand-demo-access-finance',
    scan_id: 'oppscan-demo',
    brand_name: 'Access Bank PLC',
    country: 'Nigeria',
    industry: 'Fintech / Financial Services',
    campaign_name: 'Creator Finance Trust Gap',
    campaign_type: 'marketing campaign',
    pain_point: 'Young creators are discussing inconsistent payment cycles and limited access to structured financial products for production, tax, and savings.',
    suggested_opportunity_angle: 'Create an Alignment Snapshot for a creator-finance education campaign with measurable account or product adoption signals.',
    source_url: 'https://www.accessbankplc.com/media',
    source_title: 'Access Bank creator finance opportunity',
    source_snippet: 'Public finance and creator economy signals indicate an education campaign opportunity.',
    detected_keywords: ['campaign', 'Nigeria', 'creator'],
    confidence_score: 83,
    status: 'accepted',
    accepted_brand_id: 'brand-access',
    opportunity_id: 'opp-demo-access-finance',
    reviewed_at: '2026-05-26T06:08:00.000Z',
    reviewed_by: 'admin',
    created_at: '2026-05-26T06:00:00.000Z',
  },
];

export const candidateToBusinessOpportunity = (candidate) => ({
  id: candidate.opportunity_id || candidate.id,
  candidate_id: candidate.id,
  brand_id: candidate.accepted_brand_id,
  company: candidate.brand_name,
  title: candidate.campaign_name || 'Scanned marketing opportunity',
  industry: candidate.industry,
  pain_point: candidate.pain_point,
  source: candidate.source_url,
  contact: candidate.contact_email || 'Marketing Team',
  estimated_value: 75000000,
  fit_score: candidate.confidence_score || 70,
  suggested_angle: candidate.suggested_opportunity_angle,
  status: candidate.status === 'accepted' ? 'accepted' : 'new',
});
